global:
  imageRegistry: ""
  imagePullSecrets: []

image:
  repository: grafana/grafana
  tag: "7.3.3"
  digest: ""
  pullPolicy: IfNotPresent

pvc:
  storageClassName: ""
  size: 1Gi

ingress:
  host: grafana.example.com