apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana-service
spec:
  ports:
  - port: 443
    name: https
    targetPort: 3000
  selector:
    app: grafana
  type: ClusterIP