#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  ./deploy_perf_stack.sh -n <namespace> --helm-env <env> [options]

Required:
  -n, --namespace <name>            Target namespace for perf-stack
  --helm-env <name>                 Environment values name under k8s/helm/environments/values

Host options (choose one strategy):
  --base-domain <domain>            Auto-generate hosts from namespace
  --report-host <host>              Explicit report host
  --grafana-host <host>             Explicit grafana host
  --webapp-host <host>              Explicit webapp host

Optional:
  -r, --release <name>              Helm release name (default: perf-stack)
  --chart <path>                    Helm chart path (default: k8s/helm)
  --apply-env-resources             Apply k8s/helm/environments/resources/<helm-env>/*.yaml before Helm
  --report-prefix <prefix>          Auto host prefix (default: jmeter-report)
  --grafana-prefix <prefix>         Auto host prefix (default: jmeter-grafana)
  --webapp-prefix <prefix>          Auto host prefix (default: jmeter-web)
  --master-node-label <k=v>         Optional selector for jmeter-master pod (repeatable)
  --slave-node-label <k=v>          Optional selector for jmeter-slave pods (repeatable)
  --telegraf-cluster-rbac <bool>    true for primary namespace, false for secondary (default: false)
  --skip-telegraf-rbac-subject-sync Skip auto sync of telegraf ClusterRoleBinding subject
  --skip-dependency-build           Skip helm dependency build
  --no-create-namespace             Do not pass --create-namespace
  --dry-run                         Render/validate only (adds --dry-run --debug)
  -h, --help                        Show this help

Examples:
  # Primary namespace: create cluster-scoped telegraf RBAC once
  ./deploy_perf_stack.sh -n performance-test --helm-env dr-prod \
    --base-domain mgnt.mvdis.gov.tw --telegraf-cluster-rbac true

  # Secondary namespace: avoid RBAC ownership conflicts
  ./deploy_perf_stack.sh -n performance-test2 --helm-env dr-prod \
    --base-domain mgnt.mvdis.gov.tw --telegraf-cluster-rbac false

  # Pin master/slave onto different labeled nodes
  ./deploy_perf_stack.sh -n performance-test --helm-env dr-prod \
    --base-domain mgnt.mvdis.gov.tw \
    --master-node-label role=jmeter-master \
    --slave-node-label role=jmeter-slave
EOF
}

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
release="perf-stack"
chart_path="${repo_root}/k8s/helm"
namespace=""
helm_env=""

report_prefix="jmeter-report"
grafana_prefix="jmeter-grafana"
webapp_prefix="jmeter-web"

base_domain=""
report_host=""
grafana_host=""
webapp_host=""

telegraf_cluster_rbac="false"
skip_dependency_build=0
create_namespace=1
dry_run=0
apply_env_resources=0
skip_telegraf_rbac_subject_sync=0
master_node_labels=()
slave_node_labels=()
runtime_override_dir=""
runtime_override_file=""
runtime_override_configmap="jmeter-runtime-node-selector-override"
telegraf_clusterrole_name="metrics-reader"
telegraf_clusterrolebinding_name="telegraf-metrics-reader"

parse_label_kv() {
  local label="$1"
  local -n _out_key="$2"
  local -n _out_value="$3"

  if [[ "${label}" != *=* ]]; then
    echo "[ERROR] Invalid label format: ${label} (expected key=value)" >&2
    exit 1
  fi

  _out_key="${label%%=*}"
  _out_value="${label#*=}"

  if [[ -z "${_out_key}" || -z "${_out_value}" ]]; then
    echo "[ERROR] Invalid label format: ${label} (key/value cannot be empty)" >&2
    exit 1
  fi
}

write_runtime_node_selector_override() {
  local file_path="$1"
  local key value

  mkdir -p "$(dirname "${file_path}")"
  {
    echo "# Generated by deploy_perf_stack.sh"
    echo "# Used by start_test.sh to keep runtime jmeter node placement aligned with perf-stack deployment."
    echo "global:"
    echo "  master:"
    if [[ ${#master_node_labels[@]} -gt 0 ]]; then
      echo "    nodeSelector:"
      for label in "${master_node_labels[@]}"; do
        parse_label_kv "${label}" key value
        echo "      ${key}: \"${value}\""
      done
    else
      echo "    nodeSelector: {}"
    fi

    echo "  slave:"
    if [[ ${#slave_node_labels[@]} -gt 0 ]]; then
      echo "    nodeSelector:"
      for label in "${slave_node_labels[@]}"; do
        parse_label_kv "${label}" key value
        echo "      ${key}: \"${value}\""
      done
    else
      echo "    nodeSelector: {}"
    fi
  } > "${file_path}"
}

sync_runtime_node_selector_configmap() {
  local ns="$1"
  local file_path="$2"
  local cm_name="$3"

  kubectl -n "${ns}" create configmap "${cm_name}" \
    --from-file=override.yaml="${file_path}" \
    --dry-run=client -o yaml | kubectl -n "${ns}" apply -f - >/dev/null
}

ensure_telegraf_clusterrolebinding_subject() {
  local ns="$1"
  local crb_name="$2"
  local role_name="$3"

  if ! kubectl get clusterrolebinding "${crb_name}" >/dev/null 2>&1; then
    echo "[WARN] ClusterRoleBinding ${crb_name} not found; skip telegraf SA subject sync"
    return 0
  fi

  if kubectl get clusterrolebinding "${crb_name}" -o jsonpath='{range .subjects[*]}{.kind}{":"}{.namespace}{":"}{.name}{"\n"}{end}' \
      | grep -Fxq "ServiceAccount:${ns}:telegraf"; then
    echo "[INFO] telegraf SA subject already exists in ${crb_name}: ${ns}/telegraf"
    return 0
  fi

  kubectl patch clusterrolebinding "${crb_name}" --type=json \
    -p="[{\"op\":\"add\",\"path\":\"/subjects/-\",\"value\":{\"kind\":\"ServiceAccount\",\"name\":\"telegraf\",\"namespace\":\"${ns}\"}}]" >/dev/null

  echo "[INFO] added telegraf SA subject to ${crb_name}: ${ns}/telegraf (role=${role_name})"
}

append_node_selector_set_args() {
  local prefix="$1"
  local label="$2"
  local key value

  parse_label_kv "${label}" key value

  cmd+=( --set-string "${prefix}.${key}=${value}" )
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -n|--namespace)
      namespace="$2"; shift 2 ;;
    --helm-env)
      helm_env="$2"; shift 2 ;;
    -r|--release)
      release="$2"; shift 2 ;;
    --chart)
      chart_path="$2"; shift 2 ;;
    --base-domain)
      base_domain="$2"; shift 2 ;;
    --report-prefix)
      report_prefix="$2"; shift 2 ;;
    --grafana-prefix)
      grafana_prefix="$2"; shift 2 ;;
    --webapp-prefix)
      webapp_prefix="$2"; shift 2 ;;
    --report-host)
      report_host="$2"; shift 2 ;;
    --grafana-host)
      grafana_host="$2"; shift 2 ;;
    --webapp-host)
      webapp_host="$2"; shift 2 ;;
    --telegraf-cluster-rbac)
      telegraf_cluster_rbac="$2"; shift 2 ;;
    --skip-telegraf-rbac-subject-sync)
      skip_telegraf_rbac_subject_sync=1; shift ;;
    --master-node-label)
      master_node_labels+=("$2"); shift 2 ;;
    --slave-node-label)
      slave_node_labels+=("$2"); shift 2 ;;
    --skip-dependency-build)
      skip_dependency_build=1; shift ;;
    --apply-env-resources)
      apply_env_resources=1; shift ;;
    --no-create-namespace)
      create_namespace=0; shift ;;
    --dry-run)
      dry_run=1; shift ;;
    -h|--help)
      usage; exit 0 ;;
    *)
      echo "[ERROR] Unknown option: $1" >&2
      usage
      exit 1 ;;
  esac
done

if [[ -z "${namespace}" ]]; then
  echo "[ERROR] --namespace is required" >&2
  usage
  exit 1
fi
if [[ -z "${helm_env}" ]]; then
  echo "[ERROR] --helm-env is required" >&2
  usage
  exit 1
fi
if [[ "${telegraf_cluster_rbac}" != "true" && "${telegraf_cluster_rbac}" != "false" ]]; then
  echo "[ERROR] --telegraf-cluster-rbac must be true or false" >&2
  exit 1
fi

values_file="${repo_root}/k8s/helm/environments/values/${helm_env}.yaml"
if [[ ! -f "${values_file}" ]]; then
  echo "[ERROR] Values file not found: ${values_file}" >&2
  exit 1
fi

runtime_override_dir="${repo_root}/k8s/helm/environments/runtime-overrides"
runtime_override_file="${runtime_override_dir}/${helm_env}.${namespace}.yaml"

if [[ -z "${report_host}" || -z "${grafana_host}" || -z "${webapp_host}" ]]; then
  if [[ -z "${base_domain}" ]]; then
    echo "[ERROR] Provide either all explicit hosts or --base-domain for auto host generation" >&2
    exit 1
  fi
  [[ -z "${report_host}" ]] && report_host="${report_prefix}-${namespace}.${base_domain}"
  [[ -z "${grafana_host}" ]] && grafana_host="${grafana_prefix}-${namespace}.${base_domain}"
  [[ -z "${webapp_host}" ]] && webapp_host="${webapp_prefix}-${namespace}.${base_domain}"
fi

if [[ "${skip_dependency_build}" -eq 0 ]]; then
  echo "[INFO] helm dependency build ${chart_path}"
  helm dependency build "${chart_path}" >/dev/null
fi

cmd=(
  helm upgrade --install "${release}" "${chart_path}"
  -n "${namespace}"
  -f "${values_file}"
  --set-string "report-server.ingress.host=${report_host}"
  --set-string "grafana.ingress.host=${grafana_host}"
  --set-string "webapp.ingress.host=${webapp_host}"
  --set "telegraf.rbac.createClusterScopedResources=${telegraf_cluster_rbac}"
)

if [[ ${#master_node_labels[@]} -gt 0 ]]; then
  for label in "${master_node_labels[@]}"; do
    append_node_selector_set_args "global.master.nodeSelector" "${label}"
  done
fi

if [[ ${#slave_node_labels[@]} -gt 0 ]]; then
  for label in "${slave_node_labels[@]}"; do
    append_node_selector_set_args "global.slave.nodeSelector" "${label}"
  done
fi

write_runtime_node_selector_override "${runtime_override_file}"

if [[ "${create_namespace}" -eq 1 ]]; then
  cmd+=(--create-namespace)
fi
if [[ "${dry_run}" -eq 1 ]]; then
  cmd+=(--dry-run --debug)
fi

echo "[INFO] namespace=${namespace} helm_env=${helm_env} release=${release}"
echo "[INFO] report host : ${report_host}"
echo "[INFO] grafana host: ${grafana_host}"
echo "[INFO] webapp host : ${webapp_host}"
echo "[INFO] telegraf cluster RBAC create=${telegraf_cluster_rbac}"
echo "[INFO] apply env resources      : ${apply_env_resources}"
echo "[INFO] telegraf RBAC subject sync skip=${skip_telegraf_rbac_subject_sync}"
if [[ ${#master_node_labels[@]} -gt 0 ]]; then
  echo "[INFO] jmeter-master node labels: ${master_node_labels[*]}"
else
  echo "[INFO] jmeter-master node labels: unrestricted"
fi
if [[ ${#slave_node_labels[@]} -gt 0 ]]; then
  echo "[INFO] jmeter-slave node labels : ${slave_node_labels[*]}"
else
  echo "[INFO] jmeter-slave node labels : unrestricted"
fi
echo "[INFO] runtime override file     : ${runtime_override_file}"

if [[ "${apply_env_resources}" -eq 1 ]]; then
  env_resource_dir="${repo_root}/k8s/helm/environments/resources/${helm_env}"
  if [[ ! -d "${env_resource_dir}" ]]; then
    echo "[WARN] env resource dir not found: ${env_resource_dir}"
  elif [[ "${dry_run}" -eq 1 ]]; then
    echo "[INFO] dry-run mode: skip apply env resources from ${env_resource_dir}"
  else
    mapfile -t env_resource_files < <(find "${env_resource_dir}" -maxdepth 1 -type f \( -name '*.yaml' -o -name '*.yml' \) | sort)
    if [[ ${#env_resource_files[@]} -eq 0 ]]; then
      echo "[INFO] no env resources to apply in ${env_resource_dir}"
    else
      echo "[INFO] applying env resources (${#env_resource_files[@]}) from ${env_resource_dir}"
      for f in "${env_resource_files[@]}"; do
        echo "[INFO] kubectl -n ${namespace} apply -f ${f}"
        kubectl -n "${namespace}" apply -f "${f}" >/dev/null
      done
    fi
  fi
fi

echo "[INFO] Running Helm command..."
"${cmd[@]}"

if [[ "${dry_run}" -eq 1 ]]; then
  echo "[INFO] dry-run mode: skip syncing runtime override configmap ${runtime_override_configmap}"
else
  sync_runtime_node_selector_configmap "${namespace}" "${runtime_override_file}" "${runtime_override_configmap}"
  echo "[INFO] runtime override configmap: ${runtime_override_configmap} (key: override.yaml)"
  if [[ "${skip_telegraf_rbac_subject_sync}" -eq 1 ]]; then
    echo "[INFO] skip telegraf ClusterRoleBinding subject sync by flag"
  else
    ensure_telegraf_clusterrolebinding_subject "${namespace}" "${telegraf_clusterrolebinding_name}" "${telegraf_clusterrole_name}"
  fi
fi
