apiVersion: v1
kind: Secret
metadata:
  name: bmcharbor-auth
type: kubernetes.io/dockerconfigjson
# lab 環境如果有用到harbor，auth 欄位可用: echo -n 'username:password' | base64 -w0
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "bmcharbor.mgnt.mvdis.gov.tw": {
          "username": "REPLACE_ME",
          "password": "REPLACE_ME",
          "auth": "REPLACE_BASE64_USERNAME_COLON_PASSWORD"
        }
      }
    }
