global:
  imageRegistry: "bmcharbor.mgnt.mvdis.gov.tw"
  imagePullSecrets:
    - bmcharbor-auth

jmeter:
  master:
    image:
      repository: qa_team/jmeter-k8s-jmeter-base
      tag: "5.6.3"
    resources:
      requests:
        memory: "3072Mi"
        cpu: "1000m"
      limits:
        memory: "4096Mi"
        cpu: "2000m"
  slave:
    image:
      repository: qa_team/jmeter-k8s-jmeter-base
      tag: "5.6.3"
    resources:
      requests:
        memory: "1536Mi"
        cpu: "1000m"
      limits:
        memory: "2048Mi"
        cpu: "2000m"
  pvc:
    storageClassName: nfs-client

influxdb:
  image:
    repository: qa_team/jmeter-k8s-influxdb
    tag: "1.8"

cleaner:
  image:
    repository: qa_team/jmeter-k8s-kubectl
    digest: "sha256:fd0cffa1252d718a561fee455ea5ae88781acbf31e59171ce7160ff762aa2980"
  cronjob:
    cleanupDelaySeconds: 30

report-server:
  image:
    repository: qa_team/jmeter-k8s-nginx
    tag: "1.25"
  ingress:
    host: jmeter-report-dr.mgnt.mvdis.gov.tw
    ingressClassName: nginx

telegraf:
  image:
    repository: qa_team/jmeter-k8s-telegraf
    tag: "1.5.2"

wiremock:
  image:
    repository: qa_team/jmeter-k8s-wiremock
    tag: "3.9.1-1"

grafana:
  image:
    repository: qa_team/jmeter-k8s-grafana
    tag: "7.3.3"
  ingress:
    host: jmeter-grafana-dr.mgnt.mvdis.gov.tw
    ingressClassName: nginx

webapp:we
  enabled: true
  image:
    repository: qa_team/jmeter-k8s-webapp
    tag: "2026.03.07-5"
    pullPolicy: Always
    useGlobalRegistry: true
  ingress:
    host: jmeter-web-dr.mgnt.mvdis.gov.tw
    ingressClassName: nginx