apiVersion: v1
kind: Secret
metadata:
  name: oracle-flashback-ssh
  namespace: performance-test
type: Opaque
stringData:
  host: "10.1.36.31"
  port: "22"
  username: "oracle"
  password: "oracle"  # 請根據實際環境設置密碼
  script_path: "/home/oracle/scripts"
