global:
  imageRegistry: ""
  imagePullSecrets: []

jmeter:
  enabled: false

grafana:
  ingress:
    host: grafana.example.com

report-server:
  ingress:
    host: report.example.com

wiremock:
  enabled: false

cleaner:
  enabled: true
  image:
    tag: "latest"
  cronjob:
    cleanupDelaySeconds: 30

webapp:
  enabled: true
  image:
    repository: docker.io/isaac0815/jmeter-webapp
    tag: "2026.03.10-offline1"
    pullPolicy: Always
    useGlobalRegistry: false
  ingress:
    host: jmeter-web.example.com