global:
  imageRegistry: ""
  imagePullSecrets: []

replicaCount: 1

image:
  repository: jmeter-webapp
  tag: "latest"
  digest: ""
  pullPolicy: Never
  useGlobalRegistry: false

service:
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  host: jmeter-web.example.com

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

nodeSelector: {}

reportPvc:
  claimName: jmeter-data-dir-pvc
  mountPath: /workspace/report

scenarioPvc:
  enabled: true
  existingClaim: ""
  claimName: jmeter-webapp-scenario-pvc
  keepOnUninstall: true
  mountPath: /workspace/scenario
  accessModes:
    - ReadWriteMany
  size: 10Gi
  storageClassName: ""

dataPvc:
  enabled: true
  existingClaim: ""
  claimName: jmeter-webapp-data-pvc
  keepOnUninstall: true
  mountPath: /workspace/webapp/data
  accessModes:
    - ReadWriteMany
  size: 1Gi
  storageClassName: ""

bootstrapAdmin:
  existingSecret: ""
  usernameKey: username
  passwordKey: password
  groupKey: group

timezone: "Asia/Taipei"
