global:
  imageRegistry: ""
  imagePullSecrets: []

  master:
    enabled: true
    image:
      repository: docker.io/isaac0815/jmeter-k8s-base
      tag: "5.6.3-ctg-2"
      digest: ""
      pullPolicy: IfNotPresent
    resources:
      requests:
        memory: "1024Mi"
        cpu: "500m"
      limits:
        memory: "2048Mi"
        cpu: "1000m"
    nodeSelector: {}
    affinity: {}
    tolerations: []

  slave:
    enabled: true
    image:
      repository: docker.io/isaac0815/jmeter-k8s-base
      tag: "5.6.3-ctg-2"
      digest: ""
      pullPolicy: IfNotPresent
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "768Mi"
        cpu: "1000m"
    nodeSelector: {}
    affinity: {}
    tolerations: []
  pvc:
    enabled: true
    storageClassName: nfs-csi
    size: 5Gi
    keepOnUninstall: true

slaves:
  parallelism: 1

timezone: "Asia/Taipei"

