global:
  imageRegistry: ""
  imagePullSecrets: []

image:
  repository: influxdb
  tag: "1.8"
  digest: ""
  pullPolicy: IfNotPresent

pvc:
  storageClassName: ""
  size: 5Gi

retentionDays: 14
retentionPolicyName: rp_14d
retentionShardDuration: 1d

initRetentionPolicy:
  enabled: true
  waitForReadySeconds: 120
