apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jmeter-data-dir-pvc
  {{- if .Values.pvc.keepOnUninstall }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.pvc.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}