{{- if .Values.global.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jmeter-data-dir-pvc
  {{- if .Values.global.pvc.keepOnUninstall }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  accessModes:
    - ReadWriteMany
  {{- if .Values.global.pvc.storageClassName }}
  storageClassName: {{ .Values.global.pvc.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.global.pvc.size | default "5Gi" }}
{{- end }}
