---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: influxdb
  name: influxdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
{{- if .Values.pvc.storageClassName }}
  storageClassName: {{ .Values.pvc.storageClassName }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
